// Package rank orders command candidates for the picker.
//
// The rule the whole package serves: match quality decides *whether* a command
// is a candidate, and everything else decides *which* candidate. Context can
// reorder commands that matched equally well; it can never promote a worse
// match over a better one. The first time a search for "git push" does not put
// `git push` first, the feature has lost the user.
//
// Everything here is a pure function of its arguments — no clock, no database.
// The scores in any document describing this scheme should be generated by
// running it, not worked out by hand; two attempts at doing the latter both
// produced examples that the code disagrees with.
package rank

import (
	"math"
	"strings"
	"unicode"
)

// Tier is how well a token matched, and it is a hard gate: a candidate in a
// lower tier never outranks one in a higher tier, whatever the context says.
type Tier int

const (
	TierNone Tier = iota
	// TierFuzzy: the token's characters appear in order, but not together.
	TierFuzzy
	// TierSubstring: the token appears verbatim, mid-word.
	TierSubstring
	// TierPrefix: the token starts the command, or starts any word in it.
	//
	// "Any word" rather than "the command" is what stops prefix blindness: with
	// the stricter rule, `build` ranks build-everything.sh (run once, months
	// ago) above `npm run build` (run daily, in this directory) purely because
	// of where the letters sit in the string.
	TierPrefix
)

// Match is how one candidate answered the whole query.
type Match struct {
	Tier Tier
	// Score is the mean of the per-token scores, in (0, 1].
	Score float64
}

// Tokens splits a query into terms that are matched independently, so their
// order in the query does not have to match their order in the command:
// "docker main" finds "main-app.sh docker".
//
// Empty tokens are dropped. Without that, typing a trailing space — which
// everyone does mid-thought — leaves an empty token that matches nothing and
// disqualifies every candidate.
func Tokens(q string) []string {
	return strings.Fields(strings.ToLower(q))
}

// MatchCommand scores a command against pre-tokenised query terms.
//
// Every token must match somewhere; one that does not disqualifies the
// candidate. The candidate's tier is its weakest token's, because a query is
// only as exact as its vaguest part.
func MatchCommand(command string, tokens []string) (Match, bool) {
	if len(tokens) == 0 {
		return Match{Tier: TierPrefix, Score: 1}, true
	}
	// Boundaries come from the original text and matching from the folded copy.
	// Folding first made the camelCase arm of wordStarts unreachable — nothing
	// is upper case after ToLower — so a hump silently stopped being a word
	// start and `build` matched npmRunBuild only mid-word.
	//
	// Folded rune by rune rather than with strings.ToLower, because that can
	// change how many runes a string has (İ folds to two) and the two slices are
	// indexed against each other.
	orig := []rune(command)
	text := make([]rune, len(orig))
	for i, r := range orig {
		text[i] = unicode.ToLower(r)
	}
	starts := wordStarts(orig)

	worst := TierPrefix
	total := 0.0
	for _, tok := range tokens {
		tier, score, ok := matchToken(text, starts, []rune(tok))
		if !ok {
			return Match{}, false
		}
		if tier < worst {
			worst = tier
		}
		total += score
	}
	return Match{Tier: worst, Score: total / float64(len(tokens))}, true
}

func matchToken(text []rune, starts []bool, tok []rune) (Tier, float64, bool) {
	if len(tok) == 0 {
		return TierNone, 0, false
	}
	// A prefix of the command, or of any word in it.
	for i := range text {
		if !starts[i] || !hasPrefixAt(text, i, tok) {
			continue
		}
		return TierPrefix, tokenScore(text, starts, contiguous(i, len(tok))), true
	}
	// Verbatim, but starting mid-word.
	for i := range text {
		if hasPrefixAt(text, i, tok) {
			return TierSubstring, tokenScore(text, starts, contiguous(i, len(tok))), true
		}
	}
	// In order, but scattered.
	if pos, ok := subsequence(text, tok); ok {
		return TierFuzzy, tokenScore(text, starts, pos), true
	}
	return TierNone, 0, false
}

// Character weights. A match that starts a word tells you far more about intent
// than one that lands in the middle of one.
const (
	weightWordStart  = 1.0
	weightConsective = 0.7
	weightElsewhere  = 0.4
)

// tokenScore rates one token's match: how well-placed its characters are, and
// how tightly they sit together.
func tokenScore(text []rune, starts []bool, pos []int) float64 {
	if len(pos) == 0 {
		return 0
	}
	sum := 0.0
	for i, p := range pos {
		switch {
		case starts[p]:
			sum += weightWordStart
		case i > 0 && pos[i-1] == p-1:
			sum += weightConsective
		default:
			sum += weightElsewhere
		}
	}
	placement := sum / float64(len(pos))

	// Compactness, softened by a cube root. Ungentled, this buries every match
	// in a long command: `docker compose up -d --build web` would score a
	// fraction of the same query against `up`, though it is what the user
	// wanted.
	span := pos[len(pos)-1] - pos[0] + 1
	compact := math.Cbrt(float64(len(pos)) / float64(span))
	return placement * compact
}

// subsequence finds the token's characters in order, preferring a tight match.
//
// A forward scan alone takes the first occurrence of each character, which is
// often needlessly spread out: searching "abc" in "a_____b___abc" matches
// across the whole string rather than the "abc" at the end. Scanning back from
// the end of that first match tightens it. This is fzf's V1 approach; it is not
// guaranteed optimal — fzf's V2 runs a Smith-Waterman variant for that — but it
// is O(n) and good enough to rank on until the two-phase scorer needs better.
func subsequence(text, tok []rune) ([]int, bool) {
	end := -1
	ti := 0
	for i := range text {
		if text[i] == tok[ti] {
			ti++
			if ti == len(tok) {
				end = i
				break
			}
		}
	}
	if end < 0 {
		return nil, false
	}
	pos := make([]int, len(tok))
	ti = len(tok) - 1
	for i := end; i >= 0 && ti >= 0; i-- {
		if text[i] == tok[ti] {
			pos[ti] = i
			ti--
		}
	}
	return pos, true
}

func hasPrefixAt(text []rune, i int, tok []rune) bool {
	if i+len(tok) > len(text) {
		return false
	}
	for j, r := range tok {
		if text[i+j] != r {
			return false
		}
	}
	return true
}

// wordStarts marks where words begin: the start of the string, anything after a
// separator, and a lowercase-to-uppercase hop so camelCase reads as words.
func wordStarts(text []rune) []bool {
	out := make([]bool, len(text))
	for i, r := range text {
		switch {
		case i == 0:
			out[i] = true
		case isSeparator(text[i-1]):
			out[i] = !isSeparator(r)
		case unicode.IsUpper(r):
			// A capital starts a word unless it is in the middle of a run of
			// them: npmRunBuild and awsS3Sync both begin a word at a capital
			// that follows something which is not one. A run is a single word —
			// NPM, HTTP — right up to its last capital, which starts the next
			// word when a lower-case letter follows it: parseHTTPResponse.
			out[i] = !unicode.IsUpper(text[i-1]) ||
				(i+1 < len(text) && unicode.IsLower(text[i+1]))
		}
	}
	return out
}

func isSeparator(r rune) bool {
	switch r {
	case ' ', '\t', '\n', '-', '_', '/', '.', ':', '=', ',', '|', '&', ';', '\'', '"':
		return true
	}
	return false
}

func contiguous(start, n int) []int {
	pos := make([]int, n)
	for i := range pos {
		pos[i] = start + i
	}
	return pos
}
